services:
    _defaults:
        public: false

    game.loader.txt:
        class: AppBundle\Game\Loader\TextFileLoader
        tags:
            -   name: 'game.loader'
                type: 'txt'

    game.loader.xml:
        class: AppBundle\Game\Loader\XmlFileLoader
        tags:
            -   name: 'game.loader'
                type: 'xml'

    game.word_list:
        class: AppBundle\Game\WordList
        public: true

    game.context:
        class: AppBundle\Game\GameContext
        arguments: ['@session']

    game.runner:
        class: AppBundle\Game\GameRunner
        arguments: ['@game.context', '@game.word_list']

    hangman:
        alias: 'game.runner'
        public: true